// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipgodqlupnijbyexkvsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwZ29kcWx1cG5pamJ5ZXhrdnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDg2NzcsImV4cCI6MjA2NjYyNDY3N30.NIiQWUTazjsInX9VT5VkLBugesbBe-iKCXJ-6X6G1pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);